### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by nyatindopatrick** [nyatindopatrick/Smashing-Magazine-Design#2]
Please leave your comments below.

**Comment by patriciachrysy** [comment]
Great job @nyatindopatrick! Just two remark, the white text upon the grey background cannot be seen and also you should use article tag anywhere there are articles.

**Comment by Kyle-Law** [comment]
Great job! The layout is clear and easy to follow. Overall it looks fine but just a point to note:

- Try to avoid using top:40% to align items to the center, this could have erroneous effects when you're doing responsive web design. Instead, Flexbox and Grid properties - `align-items: center` & `place-items: center;` could achieve the same effect without specifying the % or pixels. May read more on that.

In brief, it looks really good, just be careful of your choices in aligning items. Here are some summaries for you:

To align items **horizontally**, you can experiment with:
- width:100% + margin: 0 auto;
- text-align: center;
- justify-content: center + display:flex/grid

To align items **vertically**, you can experiment with:
- align-items: center + display:flex/grid;

To align items **vertically and horizontally**:
- place-items: center + display:flex/grid;

**Comment by dili021** [comment]
Good job, only thing I noticed is that in the assignment they ask us to use article tags and you didn't use it a lot.

**Comment by nyatindopatrick** [comment]
Thanks for the comments.
